### ISSUE TITLE
视图这里没有办法滚动

### ISSUE THREAD

**Issue by xie123** [wuapnjie/LayoutMaster#1]
![image](https://user-images.githubusercontent.com/7463283/38787021-3657c082-415e-11e8-8c72-c2670fd8cfd7.png)
屏幕下了，中间红框内的 视图 滚动不了  ，红框的视图会随着左右视图的滚动 变化

**Comment by wuapnjie** [comment]
额，中间的界面是一张图片，效果只有在模拟器或真机上看到

**Comment by xie123** [comment]
我的意思是 ，就算是一张图片，当屏幕没有办法显示全部的时候可不可以进行滚动哦

**Comment by xie123** [comment]
还有我点击textview 是没有办法修改 任何参数啊
