### ISSUE TITLE
Android Studio 4.1 搜不到哦

### ISSUE THREAD

**Issue by vince-styling** [wuapnjie/LayoutMaster#11]
Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.11.0-36-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.sw.FastLayoutInspector
Current Desktop: ubuntu:GNOME

**Comment by vince-styling** [comment]
老板来个微信，请教一下

**Comment by vince-styling** [comment]
看到你发布的适配 4.1 的版本了，试用了运行正常，其实我想加以下的功能：
1、左边的 View Tree 里，当前只支持搜索控件 toString 字符搜索，我想实现支持 properties 字符串搜索，比如我看到有个 textView 的 text 是 "你好"，输入你好后可定位到这个控件。
2、在某个布局上右键可快速将其显示/隐藏。

**Comment by wuapnjie** [comment]
个人简介里有，你想做的功能应该是都能实现的，可以直接下载idea的源码查看，是hook还是完全重做一个UI
